cache_ref:
  logging_level: 30
  output_mode: default
  path: ./data/cache_ref
  overwrite: true
  ra_name: ra
  dec_name: dec
  weight_name: null
  redshift_name: z
  degrees: true
  patch_file: null
  patch_name: null
  patch_num: 5
  probe_size: -1
  max_workers: null
  verbose: debug
  name: cache_ref
  config: null
cache_unk:
  logging_level: 30
  output_mode: default
  path: ./data/cache_unk
  overwrite: true
  ra_name: ra
  dec_name: dec
  weight_name: null
  redshift_name: null
  degrees: true
  patch_file: null
  patch_name: null
  patch_num: null
  probe_size: -1
  max_workers: null
  verbose: debug
  name: cache_unk
  config: null
auto_corr_lowz:
  logging_level: 30
  output_mode: default
  rmin: &id001
  - 100.0
  - 197.43504858348197
  - 389.8059840916188
  - 769.6136340726083
  - 1519.4870523363554
  rmax: &id002
  - 197.43504858348197
  - 389.8059840916188
  - 769.6136340726083
  - 1519.4870523363554
  - 3000.0000000000014
  unit: kpc
  rweight: null
  resolution: null
  zmin: 0.2
  zmax: 1.2
  num_bins: 5
  method: linear
  edges: null
  closed: right
  cosmology: Planck15
  max_workers: null
  verbose: debug
  name: auto_corr_lowz
  config: null
cross_corr_lowz:
  logging_level: 30
  output_mode: default
  rmin: *id001
  rmax: *id002
  unit: kpc
  rweight: null
  resolution: null
  zmin: 0.2
  zmax: 1.2
  num_bins: 5
  method: linear
  edges: null
  closed: right
  cosmology: Planck15
  max_workers: null
  verbose: debug
  name: cross_corr_lowz
  config: null
fit_lowz:
  logging_level: 30
  output_mode: default
  fit_rmin: 100.0
  fit_rmax: 3000.0000000000014
  auto_fit_rmin: 100.0
  auto_fit_rmax: 3000.0000000000014
  alpha: 0.0
  fit_constant: true
  use_jk_cov: false
  shrinkage: auto
  hartlap: true
  diag_eps: 0.0
  cosmology: Planck15
  transfer_function: eisenstein_hu
  verbose: debug
  name: fit_lowz
  config: null
auto_corr_highz:
  logging_level: 30
  output_mode: default
  rmin: *id001
  rmax: *id002
  unit: kpc
  rweight: null
  resolution: null
  zmin: 0.8
  zmax: 1.8
  num_bins: 5
  method: linear
  edges: null
  closed: right
  cosmology: Planck15
  max_workers: null
  verbose: debug
  name: auto_corr_highz
  config: null
cross_corr_highz:
  logging_level: 30
  output_mode: default
  rmin: *id001
  rmax: *id002
  unit: kpc
  rweight: null
  resolution: null
  zmin: 0.8
  zmax: 1.8
  num_bins: 5
  method: linear
  edges: null
  closed: right
  cosmology: Planck15
  max_workers: null
  verbose: debug
  name: cross_corr_highz
  config: null
fit_highz:
  logging_level: 30
  output_mode: default
  fit_rmin: 100.0
  fit_rmax: 3000.0000000000014
  auto_fit_rmin: 100.0
  auto_fit_rmax: 3000.0000000000014
  alpha: 0.0
  fit_constant: true
  use_jk_cov: false
  shrinkage: auto
  hartlap: true
  diag_eps: 0.0
  cosmology: Planck15
  transfer_function: eisenstein_hu
  verbose: debug
  name: fit_highz
  config: null
combine:
  logging_level: 30
  output_mode: default
  bias_mode: growth_factor
  paired: false
  normalize: true
  z_norm_max: null
  round_z_decimals: 6
  cosmology: Planck15
  transfer_function: eisenstein_hu
  verbose: debug
  name: combine
  config: null
