config: pipeline_config.yml
inputs:
  input_data: dummy.in
  input_rand: dummy.in
  rand_unk: /dev/null
  unk_corr: /dev/null
log_dir: .
modules: rail
output_dir: .
resume: false
site:
  max_threads: 2
stages:
- classname: YawCacheCreate
  module_name: rail.estimation.algos.cc_yaw
  name: cache_ref
  nprocess: 1
- classname: YawCacheCreate
  module_name: rail.estimation.algos.cc_yaw
  name: cache_unk
  nprocess: 1
- classname: YawAutoCorrelate
  module_name: rail.estimation.algos.cc_yaw
  name: autocorr
  nprocess: 1
- classname: YawCrossCorrelate
  module_name: rail.estimation.algos.cc_yaw
  name: crosscorr
  nprocess: 1
- classname: YawSummarize
  module_name: rail.estimation.algos.cc_yaw
  name: estimate
  nprocess: 1
- classname: YawCacheDrop
  module_name: rail.estimation.algos.cc_yaw
  name: drop_ref
  nprocess: 1
- classname: YawCacheDrop
  module_name: rail.estimation.algos.cc_yaw
  name: drop_unk
  nprocess: 1
